// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config } from 'dotenv';
import { defineConfig } from 'prisma/config';

const envFilePath = process.env.E2E_ENV === 'true' ? '.env.e2e' : '.env';
config({ path: envFilePath });
export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
  },
  datasource: {
    url: process.env['DATABASE_URL'],
  },
});
